<?php

return [
    'levels' => [
        ['level' => 1, 'threshold' => 0, 'title' => 'はじめまして', 'message' => 'これから一緒にがんばろう！', 'style' => 'default', 'style_name' => '基本衣装'],
        ['level' => 2, 'threshold' => 100, 'title' => '勉強仲間', 'message' => '今日も一緒に進めてうれしいな', 'style' => 'cozy-study', 'style_name' => 'おうち勉強ニット'],
        ['level' => 3, 'threshold' => 250, 'title' => 'いつもの相棒', 'message' => 'いつもの勉強、いい調子だね！', 'style' => 'study-parka', 'style_name' => 'お勉強パーカー'],
        ['level' => 4, 'threshold' => 500, 'title' => '息ぴったり', 'message' => '息ぴったりになってきたね', 'style' => 'cafe-apron', 'style_name' => '勉強カフェエプロン'],
        ['level' => 5, 'threshold' => 900, 'title' => '頼れる相棒', 'message' => '積み重ね、ちゃんと見てるよ', 'style' => 'payroll-cardigan', 'style_name' => '給与担当カーディガン'],
        ['level' => 6, 'threshold' => 1400, 'title' => '毎日の仲間', 'message' => '毎日の努力が形になってるね', 'style' => 'morning-track', 'style_name' => '朝活ジャージ'],
        ['level' => 7, 'threshold' => 2100, 'title' => 'がんばり仲間', 'message' => 'がんばる姿、すてきだよ', 'style' => 'focus-glasses', 'style_name' => '集中メガネスタイル'],
        ['level' => 8, 'threshold' => 2900, 'title' => 'ずっと相棒', 'message' => 'ここまで一緒に来られたね', 'style' => 'library-jacket', 'style_name' => '図書館ジャケット'],
        ['level' => 9, 'threshold' => 3900, 'title' => '大切なパートナー', 'message' => 'もう大切なパートナーだよ', 'style' => 'starry-academy', 'style_name' => '星空アカデミー'],
        ['level' => 10, 'threshold' => 5200, 'title' => '最高の相棒', 'message' => 'これからも最高の相棒だよ！', 'style' => 'exam-wish', 'style_name' => '合格祈願スタイル'],
    ],
    'styles' => [
        ['slug' => 'default', 'name' => '基本衣装', 'level' => 1, 'threshold' => 0],
        ['slug' => 'mint-overalls', 'name' => 'ミントサロペット', 'level' => 1, 'threshold' => 0],
        ['slug' => 'cozy-study', 'name' => 'おうち勉強ニット', 'level' => 2, 'threshold' => 100],
        ['slug' => 'cozy-pajamas', 'name' => 'おやすみルームウェア', 'level' => 2, 'threshold' => 100],
        ['slug' => 'study-parka', 'name' => 'お勉強パーカー', 'level' => 3, 'threshold' => 250],
        ['slug' => 'sunny-raincoat', 'name' => 'ひだまりレインコート', 'level' => 3, 'threshold' => 250],
        ['slug' => 'cafe-apron', 'name' => '勉強カフェエプロン', 'level' => 4, 'threshold' => 500],
        ['slug' => 'sky-sailor', 'name' => '青空セーラー', 'level' => 4, 'threshold' => 500],
        ['slug' => 'payroll-cardigan', 'name' => '給与担当カーディガン', 'level' => 5, 'threshold' => 900],
        ['slug' => 'payroll-labcoat', 'name' => '給与計算ラボコート', 'level' => 5, 'threshold' => 900],
        ['slug' => 'morning-track', 'name' => '朝活ジャージ', 'level' => 6, 'threshold' => 1400],
        ['slug' => 'autumn-poncho', 'name' => '秋色チェックポンチョ', 'level' => 6, 'threshold' => 1400],
        ['slug' => 'focus-glasses', 'name' => '集中メガネスタイル', 'level' => 7, 'threshold' => 2100],
        ['slug' => 'scholar-vest', 'name' => 'クラシック学者ベスト', 'level' => 7, 'threshold' => 2100],
        ['slug' => 'library-jacket', 'name' => '図書館ジャケット', 'level' => 8, 'threshold' => 2900],
        ['slug' => 'winter-duffle', 'name' => '冬のダッフルコート', 'level' => 8, 'threshold' => 2900],
        ['slug' => 'starry-academy', 'name' => '星空アカデミー', 'level' => 9, 'threshold' => 3900],
        ['slug' => 'festival-happi', 'name' => 'お祝いはっぴ', 'level' => 9, 'threshold' => 3900],
        ['slug' => 'exam-wish', 'name' => '合格祈願スタイル', 'level' => 10, 'threshold' => 5200],
        ['slug' => 'celebration-hakama', 'name' => '合格祝い袴', 'level' => 10, 'threshold' => 5200],
    ],
];
